### ISSUE TITLE
StateCode & CountyCode seem to be pretty sparse

### ISSUE THREAD

**Issue by stdavis** [agrc/ugs-db#11]
Tons of null values. Is this something that we need to populate using SGID data?

**Comment by steveoh** [comment]
yes. The only ones that are populated are the ones that go through the update path not the initial seed.

**Comment by stdavis** [comment]
I will add the initial calc of these values to the seeder. @steveoh has already added it to the update stuff.

**Comment by stdavis** [comment]
Make sure to use the four digit county fips code.
