### ISSUE TITLE
Field Indices

### ISSUE THREAD

**Issue by stdavis** [agrc/ugs-db#13]
On initial seed: Create indices on all fields used for filters in the web app to help with performance.

Field names can be found here: https://github.com/agrc/ugs-chemistry/wiki

**Comment by stdavis** [comment]
http://resources.arcgis.com/en/help/main/10.2/index.html#//00170000005z000000

**Comment by steveoh** [comment]
this would be a sql server index now wouldn't it?

**Comment by stdavis** [comment]
Yes

**Comment by stdavis** [comment]
@steveoh Would it be best to do this in post process after all of the data has been loaded or just add it to `createTables.sql`?

**Comment by steveoh** [comment]
I'd have to do some research to find out if it would matter. I think `createTables.sql` would be a fine spot though.

**Comment by stdavis** [comment]
Closed via #31
