### ISSUE TITLE
Fix Charge Balance Zero Divisor Error

### ISSUE THREAD

**Issue by inkenbrandt** [agrc/ugs-db#14]
Create exception that passes scenarios where the denominator the charge balance calculation are zero. 
This error came up during the WQP data import of the dbseeder:
![err](https://cloud.githubusercontent.com/assets/7726565/6941925/fc7bba6e-d840-11e4-9792-0bb89b3c6ce2.JPG)
Using:
Windows 7
Python 2.7.9

**Comment by stdavis** [comment]
@inkenbrandt So should balance be set to zero in this instance?

**Comment by stdavis** [comment]
Something like this? https://github.com/agrc/ugs-db/commit/8c10443f921387437d8a434e2004077eb4a74cb3

**Comment by inkenbrandt** [comment]
If the denominator is zero, then the result should be null.  The sum of the anions and cations should be a positive float.  If it is zeros, then there are no charges to analyze. Thanks for helping on this!
