### ISSUE TITLE
Seeding post-processing

### ISSUE THREAD

**Issue by steveoh** [agrc/ugs-db#17]
Add 4 digit county FIPS, include state, and [demelevm](https://github.com/agrc/ugs-db/issues/3)

**Comment by steveoh** [comment]
We need to use 4 digit fips

**Comment by stdavis** [comment]
@inkenbrandt I assume that the four digit FIPS should be split into the `StateCode` & `CountyCode` fields?

**Comment by inkenbrandt** [comment]
We need the four digits so you UI selects a unique county when queried.  I think a proper county code would include the prefix of the state code to make it unique.

**Comment by stdavis** [comment]
Got it. Thanks.

**Comment by stdavis** [comment]
Closed with #25
