### ISSUE TITLE
querycsv-redux

### ISSUE THREAD

**Issue by steveoh** [agrc/ugs-db#18]
[querycsv-redux](https://github.com/kdeloach/querycsv-redux/issues/2#event-353839415)

**Comment by steveoh** [comment]
We are having this [issue](http://www.azavea.com/blogs/labs/2014/03/solving-unicode-problems-in-python-2-7/), and will need to address it ourselves if the maintainer doesn't get to it by the time we need it. I did use [this approach](https://github.com/agrc/Crash-db/commit/7d46b4bdb81cd05dbae0fc82ac7340cbcd444e06#diff-951ea4e926ce2405cfd62bde40cadfeaR58) for crash but I am unsure if that is the same issue.

**Comment by stdavis** [comment]
This can be closed now, right?
