### ISSUE TITLE
Merge WQP Duplicates

### ISSUE THREAD

**Issue by inkenbrandt** [agrc/ugs-db#19]
The WQP data contains stations from the EPA STORET database that have duplicate stations.  Some stations have a _WQX suffix while others do not.  Not all STORET stations have duplicates.  For the stations with duplicates, retain the station with the WQX suffix then remove the suffix so station names are consistent.  The suffix must be removed for both the `Stations` and `Results` tables so the keys will match.  There will likely not be duplicate results, as the WQX suffix represents data that were collected after the EPA moved from the STORET legacy database to the newer WQX database.

**Comment by stdavis** [comment]
@inkenbrandt Can you provide examples of ids with and without the _WQX suffix just so that we are clear?

**Comment by inkenbrandt** [comment]
Here is a Stations Spreadsheet I downloaded from the WQP that contains multiple station duplicates: 
https://docs.google.com/a/utah.gov/spreadsheets/d/1h3_CiVfSQTWZh5DN53ueV8UGOHE5D5Gq-2wUabZh3YE/edit?usp=sharing

I highlighted the first two rows to show the example.  The station IDs are `UTAHDWQ-4904410` and `UTAHDWQ_WQX-4904410`, but everything else is the same.

**Comment by inkenbrandt** [comment]
However, it is worth noting: Do not remove the WQX suffix from the OrganizationID. UTAHDWQ vs
UTAHDWQ_WQX
