### ISSUE TITLE
Update Datasets

### ISSUE THREAD

**Issue by steveoh** [agrc/ugs-db#2]
Data updates need to be made on a schedule for

- [x] WQP
- [ ] SDWIS

Additional updates might need to be handled as a `.gdb`?

**Comment by steveoh** [comment]
@inkenbrandt how do we do the update on stations? There is no date stamp attached to them.

**Comment by inkenbrandt** [comment]
The station update might be complicated.  The easiest might be to import every station associated with the new results rows and then do some type of duplicate station check/wipe.

**Comment by steveoh** [comment]
Can you elaborate on the station duplicates?

**Comment by steveoh** [comment]
we might have some trouble using dates to get the most current...
![image](https://cloud.githubusercontent.com/assets/325813/5655731/e32c33ac-968e-11e4-8dbb-98f5e56a6753.png)

**Comment by inkenbrandt** [comment]
We can specify the largest date in the database that is less than the last date of download or that is less than `today()`.

**Comment by inkenbrandt** [comment]
The SDWIS station update query should look like this:
'''
SELECT UTV80.TINWSYS.TINWSYS_IS_NUMBER AS "OrgId",
  UTV80.TINWSYS.NAME                   AS "OrgName",
  UTV80.TINWSF.TINWSF_IS_NUMBER        AS "StationId",
  UTV80.TINWSF.NAME                    AS "StationName",
  UTV80.TINWSF.TYPE_CODE               AS "StationType",
  UTV80.TINWSF.ACTIVITY_DATE           AS "ActDate",
  UTV80.TINWSF.ACTIVITY_STATUS_CD      AS "ActStatus",
  UTV80.TINLOC.LATITUDE_MEASURE        AS "Lat_Y",
  UTV80.TINLOC.LONGITUDE_MEASURE       AS "Lon_X",
  UTV80.TINLOC.HORIZ_ACCURACY_MSR      AS "HorAcc",
  UTV80.TINLOC.HZ_COLLECT_METH_CD      AS "HorCollMeth",
  UTV80.TINLOC.HORIZ_REF_DATUM_CD      AS "HorRef",
  UTV80.TINLOC.VERTICAL_MEASURE        AS "Elev",
  UTV80.TINLOC.VERT_ACCURACY_MSR       AS "ElevAcc",
  UTV80.TINLOC.VER_COL_METH_CD         AS "ElevMeth",
  UTV80.TINLOC.VERT_REF_DATUM_CD       AS "ElevRef",
  MAX(UTV80.TINWLCAS.BOTTOM_DEPTH_MSR) AS "Depth",
  UTV80.TINWLCAS.BOTTOM_DP_MSR_UOM     AS "DepthUnit"
FROM UTV80.TINWSF
JOIN UTV80.TINWSYS
ON UTV80.TINWSF.TINWSYS_IS_NUMBER = UTV80.TINWSYS.TINWSYS_IS_NUMBER
JOIN UTV80.TINLOC
ON UTV80.TINWSF.TINWSF_IS_NUMBER = UTV80.TINLOC.TINWSF_IS_NUMBER
LEFT JOIN UTV80.TINWLCAS
ON UTV80.TINWSF.TINWSF_IS_NUMBER    = UTV80.TINWLCAS.TINWSF_IS_NUMBER
WHERE (UTV80.TINWSF.TYPE_CODE       = 'SP'
OR UTV80.TINWSF.TYPE_CODE           = 'WL')
AND UTV80.TINLOC.LATITUDE_MEASURE  != 0
AND UTV80.TINWSF.ACTIVITY_DATE      > TO_DATE('2014-01-01','YYYY-MM-DD')
AND UTV80.TINWSF.ACTIVITY_STATUS_CD <>'I'
GROUP BY UTV80.TINWSF.TINWSF_IS_NUMBER,
  UTV80.TINWSF.NAME,
  UTV80.TINWSF.TYPE_CODE,
  UTV80.TINWSF.ACTIVITY_DATE,
  UTV80.TINWSF.ACTIVITY_STATUS_CD,
  UTV80.TINWSYS.TINWSYS_IS_NUMBER,
  UTV80.TINWSYS.NAME,
  UTV80.TINLOC.LATITUDE_MEASURE,
  UTV80.TINLOC.LONGITUDE_MEASURE,
  UTV80.TINLOC.SRC_MAP_SCALE_NUM,
  UTV80.TINLOC.HORIZ_ACCURACY_MSR,
  UTV80.TINLOC.HZ_COLLECT_METH_CD,
  UTV80.TINLOC.HORIZ_REF_DATUM_CD,
  UTV80.TINLOC.VERTICAL_MEASURE,
  UTV80.TINLOC.VERT_ACCURACY_MSR,
  UTV80.TINLOC.VER_COL_METH_CD,
  UTV80.TINLOC.VERT_REF_DATUM_CD,
  UTV80.TINWLCAS.BOTTOM_DEPTH_MSR,
  UTV80.TINWLCAS.BOTTOM_DP_MSR_UOM
'''

**Comment by steveoh** [comment]
@inkenbrandt can you remind me how to do this?

> We can query our database for the stations that would be in the download from the WQP. If the stations are found in our database, then we can skip the import of the stations (not the results). If the stations are not found, then we can import the new stations.

I thought I had the vision of how to do this, but I think i was just being optimistic. I don't see how to get stations from the result query. Can we use the most recent date from results to download stations? The date range seems to work on stations even though the stations doesn't carry a date field. Is this something you could coerce the WQP folks to add or inquire how they are doing that?

**Comment by inkenbrandt** [comment]
We can use the most recent dates to download stations, and that is how we should do it.  However, that download will likely produce duplication, as we might download stations that are already in our database.
