### ISSUE TITLE
SampleDate cleansing

### ISSUE THREAD

**Issue by steveoh** [agrc/ugs-db#26]
This was found in the previous version. 

!![sampledate](https://cloud.githubusercontent.com/assets/325813/5655731/e32c33ac-968e-11e4-8dbb-98f5e56a6753.png)

We use the `SampleDate` for querying a service to get new results. 

@inkenbrandt Would it be safe to **replace** dates with `None` or **remove** _the entire row_ that contains dates that are in the future when the script was run?

**Comment by inkenbrandt** [comment]
better to replace dates with None

**Comment by steveoh** [comment]
closed with #32
