### ISSUE TITLE
Remove excess whitespace

### ISSUE THREAD

**Issue by steveoh** [agrc/ugs-db#27]
remove whitespace on input rows values.

the pythonic way would be to try and ask for forgiveness

```python
try:
    value = value.strip()
except:
    pass
```

**Comment by stdavis** [comment]
This [is already in version2](https://github.com/agrc/ugs-db/blob/version2/src/dbseeder/services.py#L55) so I'm not sure how the padding is getting in.

**Comment by steveoh** [comment]
we are using nvarchar as the text type which don't reserve the storage. im not sure what is up... what fields are you seeing this on and how?

**Comment by stdavis** [comment]
Closed with #29
