### ISSUE TITLE
Elevation Values

### ISSUE THREAD

**Issue by steveoh** [agrc/ugs-db#3]
Extract values from 10m resolution DEM (Preferably NED) to the stations. 

If possible, we should add this elevation to the feature class's z information (something like feature to 3D by attribute).

**Comment by steveoh** [comment]
If the station already has an elevation value then what?

**Comment by stdavis** [comment]
@inkenbrandt I see the following elevation-related fields in the stations table:
`Elev`
`ElevUnit`
`ElevAcc`
`ElevAccUnit`
`ElevMeth`
`ElevRef`

Which of these do you want us to populate and with what values?

**Comment by inkenbrandt** [comment]
Some of the values in these fields are already populated. If it is at all possible, I would prefer to retain existing values.  For the NULL values:
`Elev` = Station Elevation - Derived from USGS NED 10m DEM
`ElevUnit` = the units of the elevation = `meters`
`ElevAcc` = accuracy of dataset - NED accuracy varies - leave blank
`ElevAccUnit = leave blank
`ElevMeth` = `Other`

**Comment by stdavis** [comment]
@inkenbrandt Would this service be an acceptable source for elevation values?
http://services.nationalmap.gov/arcgis/rest/services/SmallScale100Meter/SmallScaleElevationWMS/MapServer

**Comment by stdavis** [comment]
That's not an elevation service. If you can find an elevation service that we can hit that would be great. I don't think that we are going to want to pay to host a 10m DEM for surrounding states. It would be much better to find a service even though it may slow down the script.

**Comment by stdavis** [comment]
What about this service? http://nationalmap.gov/epqs/

**Comment by inkenbrandt** [comment]
There is also this:
http://services.nationalmap.gov/arcgis/services/3DEPElevationIndex/MapServer/WMSServer?request=GetCapabilities&service=WMS 

I think that is an elevation service.

I found it here:
http://viewer.nationalmap.gov/example/services/serviceList.html

**Comment by inkenbrandt** [comment]
The EPQS is great.  I think it is our best bet

**Comment by stdavis** [comment]
@inkenbrandt Some of the existing elevation values do not look right to me. For example:
Elev: 1958097536 or 0. Do you want me to replace those values that fall outside of a certain range of acceptable values?

**Comment by stdavis** [comment]
Closed with #28
