### ISSUE TITLE
Datefield in ArcMap

### ISSUE THREAD

**Issue by steveoh** [agrc/ugs-db#34]
It looks like the date fields are not displaying in arcmap. We need to get with Michael and see how SDE handles dates with arcmap and try to get them to play nicer together. 

@stdavis have you pointed the map service to the new db? Do the date values come back with the map service?

**Comment by stdavis** [comment]
I had to manually add the date fields to the sql query in the query layer and then they showed up without problems. Not sure why they got stripped when dragging and dropping from catalog.

**Comment by stdavis** [comment]
I think that we need to switch from `date` to `datetime2(7)`. It appears that ESRI products do not support reading from a `date` data type field.

Ref: http://gis.stackexchange.com/questions/62267/problem-viewing-sql-2008-date-field
Doc: http://desktop.arcgis.com/en/desktop/latest/manage-data/databases/dbms-data-types-supported.htm#ESRI_SECTION1_5B33DF763064489295DC794BC872957D

I've tested out this change on my local database and it solves the date problems that we are having. I'll make the change to the test DB as well.
