### ISSUE TITLE
version2 --> master

### ISSUE THREAD

**Issue by stdavis** [agrc/ugs-db#35]
I think that it's time to move version2 to master unless there's stuff there that we still need.

**Comment by steveoh** [comment]
yeeeeeeah. Do we branch master into version 1, then delete master, then branch version2 into master and call it a day?

**Comment by stdavis** [comment]
I'd be up for giving that a try.

**Comment by stdavis** [comment]
`updating` was re-branched as `version1` and `version2` was re-branched as `master`.
