### ISSUE TITLE
deleting cursor and connection unneeded?

### ISSUE THREAD

**Issue by stdavis** [agrc/ugs-db#38]
[These lines](https://github.com/agrc/ugs-db/blob/master/src/dbseeder/dbseeder.py#L53-L57) throw an error if the variable hasn't been assigned yet. For example, "UnboundLocalError: local variable 'cursor' referenced before assignment" (thrown from line 54).

I would propose that we remove this code block completely since it's the end of the code path anyway and the variables will be deleted when the script exits. @steveoh What do you think?

**Comment by steveoh** [comment]
that's interesting. I'd prefer to initialize the variables earlier to None. I don't want to keep open connections to the db if anything goes wrong eariler.
