### ISSUE TITLE
WQP Results data parsed incorrectly

### ISSUE THREAD

**Issue by inkenbrandt** [agrc/ugs-db#47]
Some samples are parsed incorrectly, likely because of quotes in one of the rows.

One example is `SampleID nwisnv.01.00901373` (a sample from `StationID USGS-362735114154501`)

The `Param` values for everything in this sample is `USGS`, which is not a possible parameter.  I noticed that `ActivityCommentText` is `"A-2400004 Filter lot Q625 L-2400004 Received August 27, 2009..  verified FA btl not received,paa,9/2/09"` which, unlike the correctly parsed samples from this station, includes quote characters.  My guess is these are causing problems.

I downloaded the data from WQP, and it is correctly parsed in the download.

**Comment by inkenbrandt** [comment]
Other examples: 
* `nwisnv.01.00800377` from station `USGS-355919114444301`
* `nwisnv.01.00900323` from station `USGS-361448114055201`
Both of which also have `"` symbols in one of the fields.  All of these problem data appear to be coming from `OrgId = USGS-NV`

**Comment by steveoh** [comment]
could you send a csv file that has those problem rows. I only have test data and i'm not sure those problem records are there.
