### ISSUE TITLE
Dates

### ISSUE THREAD

**Issue by steveoh** [agrc/ugs-db#50]
`Cast('0213-12-03' as datetime)` just broke a sdwis import. 

Why are we using datetime? The datetime range is from January 1, 1753, through December 31, 9999. if we use the date type it goes to 0001-01-01 through 9999-12-31.

Granted this is a typo, but we don't want it to fail the script.

@inkenbrandt, thoughts?

**Comment by inkenbrandt** [comment]
I think we need date time for query and geospatial compatibility

**Comment by steveoh** [comment]
It will be a datetime in the db for query and arcmap but we do not have times for the seed of these programs so we can parse it as a plain date but store it as a datetime

**Comment by inkenbrandt** [comment]
The input data contains a time field as well.  How is that being handled?

**Comment by steveoh** [comment]
Dates before 1800 should be dropped.

**Comment by inkenbrandt** [comment]
Maybe also drop dates after present date `datetime.date.today()`

**Comment by steveoh** [comment]
we are already doing that
