### ISSUE TITLE
UGS/DOGM Update function

### ISSUE THREAD

**Issue by inkenbrandt** [agrc/ugs-db#56]
Command that allows user to enter command to update the `UGS` and `DOGM` databases using geodatabase data.  Once the initial data are seeded, I want the option to append new data to the existing data.  There should be a way to check for and remove duplicate stations and results data.

**Comment by steveoh** [comment]
would we use a date string to find new ones or could we "update" via seed code with an updated gdb that is only new data?

**Comment by inkenbrandt** [comment]
updated gdb that is only new data
