### ISSUE TITLE
Pass seed data folder to file lengths

### ISSUE THREAD

**Issue by inkenbrandt** [agrc/ugs-db#6]
I know this is a simple change, and utltimately, it will be different anyways, but make sure that the file path of the variable seed_data (`C:\\Projects\\GitHub\\ugs-chemistry\\scripts\\dbseeder\\data`) in <a href= https://github.com/agrc/ugs-db/blob/master/src/dbseeder/dbseeder.py#L91>`dbseeder.Seeder.field_lengths()` </a> is consistent with <a href=https://github.com/agrc/ugs-db/blob/master/src/dbseeder/dbseeder.py#L179</a> other `seed_data` file paths.

**Comment by steveoh** [comment]
If you are getting into that profiler code then you are invoking the module incorrectly. The seed data should come from [here](https://github.com/agrc/ugs-db/blob/master/src/dbseeder/__main__.py#L38) by using [these commands](https://github.com/agrc/ugs-db#usage). I would assume that the fields lengths is not using the value passed in but that is the issue that should really be fixed.

**Comment by steveoh** [comment]
Pass in parent folder to file lengths

https://github.com/agrc/ugs-db/blob/master/src/dbseeder/dbseeder.py#L89

optionally make it work on more than just the wqp program.
