### ISSUE TITLE
Adjust SDWIS Nitrate Concentrations 

### ISSUE THREAD

**Issue by inkenbrandt** [agrc/ugs-db#8]
Upon close examination of Nitrate values in the SDWIS database, I found that in the `Stations` table even if the `Parameter` field was equal to `NITRATE` and the `Unit` field was equal to `mg/l`, the nitrate values are actually in units of `mg/l as n`.  

This means that all of the nitrate values in the `SDWIS` database need to be converted via the code:
```python
elif chemical == 'nitrate' and unit == 'mg/l' and datasource=='SDWIS':
    return self.calculate_amount(current_amount, 4.426802887), \
    milli_per_liter, original_chemical
```
This piece of code would have to be inserted <a href=https://github.com/agrc/ugs-db/blob/master/src/dbseeder/services.py#L219>here</a>.  It uses the `DataSource` field in the `Results` table, which means that `DataSource` should be assigned before the `Normalizer` class is called, and that datasource will have to be added to the `normalize_unit` function <a href=https://github.com/agrc/ugs-db/blob/master/src/dbseeder/services.py#L169>here</a>.

**Comment by steveoh** [comment]
@inkenbrandt this should only happen to `SDWIS` meaning that if it ran on `WQP` or other programs it would have adverse affects?

**Comment by inkenbrandt** [comment]
True

**Comment by steveoh** [comment]
The code links you pasted were not conincal links so they don't make a whole lot of sense anymore. As well, the code for performing these calculations has been refactored. 

I placed this code into a spot I believe is correct but for clarification:
the output unit will continue to be `mg/l`

**Comment by inkenbrandt** [comment]
There was a mistake in the code above `nitrite` for that bit should have said `nitrate`.

**Comment by steveoh** [comment]
Is this ready to be closed @inkenbrandt?

**Comment by inkenbrandt** [comment]
Yes
